feat: gql schema file
reearth/reearth-cms pull request #122
Opened 2022-07-22 00:20 UTC by mimoham24

2022-07-22 05:46 UTC, yk-eukarya reviewed
Do not forget to configure the resolver in the `gqlgen.yml` file under the `models` section

2022-07-22 05:47 UTC, yk-eukarya commented on server/schemas/item.graphql
> +  itemId: ID!
```suggestion
```

2022-07-25 13:53 UTC, yk-eukarya approved these changes
LGTM

2022-07-26 03:42 UTC, rot1024 requested changes

2022-07-26 03:42 UTC, rot1024 commented on server/schemas/item.graphql
> +    projectId: ID!
```suggestion
    modelId: ID!
```

Remember relation between domain models: `Project *- Model - Schema *- Item`. Also note that this query returns latest versions of each item.

2022-07-26 03:42 UTC, rot1024 commented on server/schemas/item.graphql
> +  checkItemKeyAvailability(key: String!): KeyAvailability!
```suggestion
```

There should be no need to check the key in the item.

2022-07-26 03:42 UTC, rot1024 commented on server/schemas/item.graphql
> +  deleteItem(input: DeleteItemInput!): DeleteProjectPayload
```suggestion
  createItem(input: CreateItemInput!): ItemPayload
  updateItem(input: UpdateItemInput!): ItemPayload
  deleteItem(input: DeleteItemInput!): DeleteItemPayload
```

2022-07-26 03:42 UTC, rot1024 commented on server/schemas/item.graphql
> +type ItemValue {
```suggestion
type ItemField {
```

2022-07-26 03:42 UTC, rot1024 commented on server/schemas/item.graphql
> +}
Mark "force resolver" for `lastestVersion` and `versions`. `lastestVersion` resolver should returns the latest version if the struct has already `versions`.

```suggestion
  publicVersion: String!
  createdAt: DateTime!
  updatedAt: DateTime!
  lastestVersion: ItemVersion
  versions: [ItemVersion!]!
}

type ItemVersion {
  version: String!
  parent: [String!]!
  ref: [String!]!
  fields: [ItemField!]!
}
```

2022-07-27 06:40 UTC, rot1024 approved these changes

2022-07-27 06:40 UTC, rot1024 commented on server/schemas/item.graphql
> +  latestVersion: ItemVersion
```suggestion
  createdAt: DateTime!
  updatedAt: DateTime!
  latestVersion: ItemVersion
  publicVersion: ItemVersion
```

2022-07-27 09:16 UTC, merged