feat(server): item infrastructure
reearth/reearth-cms pull request #178
Opened 2022-08-26 00:54 UTC by mimoham24

# Overview

## What I've done

## What I haven't done

## How I tested

## Screenshot

## Which point I want you to review particularly

## Memo

2022-09-07 07:20 UTC, rot1024 requested changes

2022-09-07 07:20 UTC, rot1024 commented on server/internal/infrastructure/memory/item.go
> +	err  error
```suggestion
	data *memorygit.VersionedSyncMap[item.ID, *item.Item]
```

use `memorygit.VersionedSyncMap`

2022-09-07 07:20 UTC, rot1024 commented on server/pkg/item/item.go
> +	return i.fields
```suggestion
	return slices.Clone(i.fields)
```

2022-09-07 07:20 UTC, rot1024 commented on server/pkg/item/list.go
> +type List []*Item
Is it used?

2022-09-07 07:20 UTC, rot1024 commented on server/pkg/item/field.go
> +	return f.schemaFieldID
add test

2022-09-07 07:20 UTC, rot1024 commented on server/pkg/item/field.go
> +	return f.valueType
add test

2022-09-07 07:20 UTC, rot1024 commented on server/pkg/item/field.go
> +	return f.value
add test

2022-09-07 07:20 UTC, rot1024 commented on server/pkg/item/builder.go
> +	b.i.fields = fs
```suggestion
	b.i.fields = slices.Clone(fs)
```

2022-09-07 07:20 UTC, rot1024 commented on server/internal/infrastructure/mongo/mongodoc/item.go
> +}
See https://github.com/reearth/reearth-cms/blob/main/server/internal/infrastructure/mongo/mongodoc/model.go#L63

```suggestion
type ItemConsumer = mongox.SliceFuncConsumer[*ItemDocument, *item.Item]

func NewItemConsumer() *ItemConsumer {
	return NewComsumer[*ItemDocument, *item.Item]()
}
```

2022-09-07 07:23 UTC, rot1024 requested changes

2022-09-07 07:23 UTC, rot1024 commented on server/internal/infrastructure/mongo/item.go
> +	c := &mongox.SliceConsumer[mongodoc.ItemDocument]{}
```suggestion
	c := mongox.NewItemConsumer()
```

2022-09-07 07:23 UTC, rot1024 commented on server/internal/infrastructure/mongo/item.go
> +	c := &mongox.SliceConsumer[mongodoc.ItemDocument]{}
```suggestion
	c := mongox.NewItemConsumer()
```

2022-09-07 21:28 UTC, mimoham24 commented on server/pkg/item/list.go
> +type List []*Item
yes, it's used in mongo layer

2022-09-13 06:25 UTC, rot1024 requested changes

2022-09-13 06:25 UTC, rot1024 commented on server/internal/infrastructure/mongo/item_test.go
> +	assert.Error(t, err)
```suggestion
	assert.Equal(t, rerror.ErrNotFound, err)
```

2022-09-13 06:25 UTC, rot1024 commented on server/internal/infrastructure/mongo/mongodoc/item.go
> +type ItemFieldDoc struct {
```suggestion

type ItemFieldDoc struct {
```

2022-09-13 06:25 UTC, rot1024 commented on server/internal/infrastructure/mongo/item_test.go
> +}
`FindBySchema`, `FindAllVersionsByID`, `FindByIDs` are not tested. Can you add unit tests for them?

2022-09-16 06:18 UTC, rot1024 approved these changes

2022-09-16 06:19 UTC, merged