feat(server): integration controllers
reearth/reearth-cms pull request #221
Opened 2022-09-08 22:49 UTC by yk-eukarya

# Overview

## What I've done

## What I haven't done

## How I tested

## Screenshot

## Which point I want you to review particularly

## Memo

2022-09-14 10:11 UTC, rot1024 requested changes

2022-09-14 10:11 UTC, rot1024 commented on server/pkg/integration/integration.go
>  	return i.webhook
```suggestion
	return slices.Clone(i.webhooks)
```

rename `webhook` filed to `webhooks`

2022-09-14 10:11 UTC, rot1024 commented on server/internal/adapter/gql/resolver_mutation_integration.go
> +func FromPtr[T any](pointer *T, defaultValue T) T {
should use lo.FromPtrOr https://github.com/samber/lo#fromptror

2022-09-14 10:11 UTC, rot1024 commented on server/internal/adapter/gql/gqlmodel/convert_integration.go
> +		},
If it is not the user's integration, config should be nil.

2022-10-05 05:26 UTC, yk-eukarya commented
Closed by #240

2022-10-05 05:26 UTC, closed without merging