feat(server): support tag as a schema fields datatype
reearth/reearth-cms pull request #802
Opened 2023-08-23 08:28 UTC by mimoham24

2023-08-29 09:02 UTC, rot1024 requested changes

2023-08-30 01:45 UTC, mimoham24 commented on server/pkg/schema/field_tag.go
> +		tmap[i.Name()] = struct{}{}
are we allowing multiple tags? for example can 2 tags with the name `Apple` exist in the same schema field?

2023-08-30 02:23 UTC, rot1024 commented on server/pkg/schema/field_tag.go
> +		tmap[i.Name()] = struct{}{}
You may want to check for duplicates in both ID and name.

---

By the way, if you want to implement Notion-like tags, you can do the following (this is just for reference)

1. the API accepts tags by name.
2. process to convert the tag to an ID based on the name. Add the new tag to the schema.TagField if necessary; you may want to add a method to schema.TagField. 3.
3. check for duplicate tags by both ID and name with ValidateMultiple.
4. save any changes to the schema.

Translated with www.DeepL.com/Translator (free version)

2023-08-30 03:00 UTC, rot1024 approved these changes

2023-08-30 03:02 UTC, merged