feat(web): search referenced item by title value
reearth/reearth-cms pull request #954
Opened 2023-11-16 09:55 UTC by caichi-t

## What I've done
- Changed title of referenced items modal
- Fixed the modal style
- Added function that searching the items by Title of them

## Memo
Currently, the id of the Title column is got in a roundabout way, so it might be better to change it.

2023-11-16 10:30 UTC, caichi-t commented on web/src/components/organisms/Project/Content/ContentList/hooks.ts
> +      searchParams.set("page", "1");
Fixed page returns to page 1 after searching on a page other than page 1 on main table.

2023-11-20 06:37 UTC, nourbalaha requested changes

2023-11-20 06:37 UTC, nourbalaha commented on web/src/components/molecules/Content/Form/ReferenceFormItem/index.tsx
> +    }
```suggestion
    onSearchTerm?.("");
```

2023-11-20 06:37 UTC, nourbalaha commented on web/src/components/molecules/Content/LinkItemModal/index.tsx
> +  const onInput = (e: ChangeEvent<HTMLInputElement>) => {
```suggestion
  const handleInput = (e: ChangeEvent<HTMLInputElement>) => {
```

2023-11-20 06:37 UTC, nourbalaha commented on web/src/components/molecules/Content/LinkItemModal/index.tsx
> +        onChange={onInput}
```suggestion
        onChange={handleInput}
```

2023-11-20 06:37 UTC, nourbalaha commented on web/src/components/organisms/Project/Content/ContentDetails/hooks.ts
> +  const [searchTerm, setSearchTerm] = useState<string>("");
```suggestion
  const [searchTerm, setSearchTerm] = useState("");
```

2023-11-20 07:10 UTC, nourbalaha approved these changes

2023-11-20 07:10 UTC, merged